language: java

jdk:
  - oraclejdk8

cache:
  directories:
    - node
    - node_modules

branches:
  only:
    - feature/standalone-selenium

before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x24"
  - sleep 3
  - "wget -q -O selenium-server-standalone-3.3.1.jar http://selenium-release.storage.googleapis.com/3.3/selenium-server-standalone-3.3.1.jar"
  - "java -jar selenium-server-standalone-3.3.1.jar > /dev/null &"
  - sleep 5

script:
  mvn verify -B

after_success:
  - bash <(curl -s https://codecov.io/bash)
