language: java

jdk:
  - oraclejdk8

before_install:
  - echo 'sonatypeUsername=' >> gradle.properties
  - echo 'sonatypePassword=' >> gradle.properties

after_success:
  - bash <(curl -s https://codecov.io/bash)
